set_schedule:
  target:
    entity:
      integration: cozytouch
      domain: climate
  fields:
    program:
      required: true
      example: cooling
      selector:
        select:
          options:
            - heating
            - cooling
    days:
      required: true
      example: '["monday", "tuesday"]'
      selector:
        select:
          multiple: true
          options:
            - monday
            - tuesday
            - wednesday
            - thursday
            - friday
            - saturday
            - sunday
    slots:
      required: true
      example: |
        - time: "00:00"
          temperature: 26
        - time: "07:00"
          temperature: 24
      selector:
        object:
set_away_mode:
  target:
    entity:
      integration: cozytouch
      domain: climate
  fields:
    start:
      example: "2026-12-24 08:00:00"
      selector:
        datetime:
    end:
      example: "2027-01-02 18:00:00"
      selector:
        datetime:
    duration:
      example: "10 00:00:00"
      selector:
        duration:
          enable_day: true
    temperature:
      example: 12
      selector:
        number:
          min: 5
          max: 30
          step: 0.5
          unit_of_measurement: "°C"
clear_away_mode:
  target:
    entity:
      integration: cozytouch
      domain: climate
